# interpreter/interpreter.py
# Executes the AST generated by the parser

class Interpreter:
    # executes LOLCode AST and manages runtime state
    
    def __init__(self, ast, symbol_table):
        self.ast = ast
        self.symbol_table = symbol_table
        self.output = []  # store VISIBLE output
        self.input_buffer = [] # for GIMMEH 
        self.execution_pointer = 0
        
        # create the implicit IT variable
        if "IT" not in self.symbol_table.symbols:
            self.symbol_table.symbols["IT"] = None
    
    def execute(self):
            if self.ast.type != 'program':
                raise RuntimeError("AST root must be a program node")
            executable_nodes = self.ast.children
            while self.execution_pointer < len(executable_nodes):
                node = executable_nodes[self.execution_pointer]
                result = self.execute_node(node)
                if isinstance(result, dict) and result.get('status') == 'awaiting_input':
                    return result

                self.execution_pointer += 1
            return {'status': 'completed', 'output': self.output}
        
    def execute_node(self, node):
        # execute a single AST node
        if node is None:
            return None
        
        node_type = node.type

        # variable declaration block
        if node_type == 'variable_declaration_block':
            for child in node.children:
                self.execute_node(child)
            return None

        # variable declaration (I HAS A)
        elif node_type == 'variable_declaration':
            var_name = node.value
            if node.children:
                # has initialization (ITZ)
                initial_value = self.evaluate_expression(node.children[0])
                self.symbol_table.symbols[var_name] = initial_value
            else:
                # no initialization set to NOOB
                self.symbol_table.symbols[var_name] = None
            return None
        
        # assignment statement
        elif node_type == 'assignment':
            var_name = node.value
            new_value = self.evaluate_expression(node.children[0])
            self.symbol_table.symbols[var_name] = new_value
            return None
        
        # print statement (VISIBLE)
        elif node_type == 'print_statement':
            output_parts = []
            for child in node.children:
                value = self.evaluate_expression(child)
                # convert to string for output
                output_parts.append(self.to_yarn(value))
            output_line = "".join(output_parts)
            self.output.append(output_line)
            # store result in IT
            self.symbol_table.symbols["IT"] = output_line
            return None

        elif node_type == 'switch_statement':
            it_value = self.symbol_table.symbols.get("IT")

            case_executed = False
            breaking = False

            for child in node.children:
                if child.type == 'case':
                    # literal in case
                    case_literal = self.evaluate_expression(child.children[0])

                    if not case_executed and case_literal == it_value:
                        # execute this block
                        for stmt in child.children[1:]:
                            if stmt.type == "break":
                                breaking = True
                                break
                            self.execute_node(stmt)
                        case_executed = True
                    
                    if breaking:
                        break

                elif child.type == 'default_case' and not case_executed:
                    for stmt in child.children:
                        self.execute_node(stmt)
                    break

            return None

    
        #O RLY? / YA RLY / NO WAI
        elif node_type == 'orly_statement':
            # IT should already hold the condition
            it_value = self.symbol_table.symbols.get("IT", None)
            if self.to_troof(it_value):
                # Execute YA RLY block
                for child in node.children:
                    if child.type == 'ya_rly':
                        for stmt in child.children:
                            if stmt.type == 'break':
                                return {'type': 'break'}
                            result = self.execute_node(stmt)
                            if isinstance(result, dict) and result.get('type') == 'break':
                                return result
                        break
            else:
                # Execute NO WAI block if exists
                for child in node.children:
                    if child.type == 'no_wai':
                        for stmt in child.children:
                            if stmt.type == 'break':
                                return {'type': 'break'}
                            result = self.execute_node(stmt)
                            if isinstance(result, dict) and result.get('type') == 'break':
                                return result
                        break
            return None
        
        #Added for User Input GIMMEH
        elif node_type == 'input_statement':
            if not self.input_buffer:
                return {'status': 'awaiting_input', 'variable': node.value}
            user_input = self.input_buffer.pop(0)
            var_name = node.value
            self.symbol_table.symbols[var_name] = user_input
            return None 
        
        # Loop statement
        elif node_type == 'loop':
            return self.execute_loop(node)
        
        # Expression statement (standalone expression, result goes to IT)
        elif node_type == 'expression_statement':
            result = self.evaluate_expression(node.children[0])
            self.symbol_table.symbols["IT"] = result
            return None
        
        else:
            # for other node types, try to evaluate as expression
            return self.evaluate_expression(node)
    
    def evaluate_expression(self, node):
        # evaluate an expression and return its value
        if node is None:
            return None
        
        node_type = node.type
        
        # Literals
        if node_type == 'literal_numbr':
            return int(node.value)
        
        elif node_type == 'literal_numbar':
            return float(node.value)
        
        elif node_type == 'literal_yarn':
            return str(node.value)
        
        elif node_type == 'literal_troof':
            return node.value == 'WIN'
        
        # Variable reference
        elif node_type == 'variable':
            var_name = node.value
            if var_name not in self.symbol_table.symbols:
                raise RuntimeError(f"Variable '{var_name}' not declared")
            value = self.symbol_table.symbols[var_name]
            # Store in IT
            self.symbol_table.symbols["IT"] = value
            return value
        
        # Binary operations
        elif node_type == 'binary_operation':
            operation = node.value
            left = self.evaluate_expression(node.children[0])
            right = self.evaluate_expression(node.children[1])
            result = self.execute_binary_operation(operation, left, right)
            # Store result in IT
            self.symbol_table.symbols["IT"] = result
            return result
        
        else:
            raise RuntimeError(f"Unknown expression type: {node_type}")
    
    def execute_binary_operation(self, operation, left, right):
        # execute a binary operation
        
        # Arithmetic operations
        if operation == 'SUM OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            result = left_num + right_num
            # return NUMBAR if either operand is NUMBAR, else NUMBR
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        elif operation == 'DIFF OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            result = left_num - right_num
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        elif operation == 'PRODUKT OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            result = left_num * right_num
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        elif operation == 'QUOSHUNT OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            if right_num == 0:
                raise RuntimeError("Division by zero")
            result = left_num / right_num
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        elif operation == 'MOD OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            if right_num == 0:
                raise RuntimeError("Modulo by zero")
            result = left_num % right_num
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        elif operation == 'BIGGR OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            result = max(left_num, right_num)
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        elif operation == 'SMALLR OF':
            left_num = self.to_number(left)
            right_num = self.to_number(right)
            result = min(left_num, right_num)
            return result if isinstance(left_num, float) or isinstance(right_num, float) else int(result)
        
        # Comparison operations
        elif operation == 'BOTH SAEM':
            return left == right
        
        elif operation == 'DIFFRINT':
            return left != right
        
        # Boolean operations
        elif operation == 'BOTH OF':
            return self.to_troof(left) and self.to_troof(right)
        
        elif operation == 'EITHER OF':
            return self.to_troof(left) or self.to_troof(right)
        
        elif operation == 'WON OF':
            return self.to_troof(left) != self.to_troof(right)
        
        else:
            raise RuntimeError(f"Unknown operation: {operation}")
    
    # Type conversion helpers
    def to_number(self, value):
        # convert value to NUMBR or NUMBAR
        if value is None:
            raise RuntimeError("Cannot convert NOOB to number")
        
        if isinstance(value, bool):
            return 1 if value else 0
        
        if isinstance(value, int):
            return value
        
        if isinstance(value, float):
            return value
        
        if isinstance(value, str):
            # try to convert string to number
            try:
                if '.' in value:
                    return float(value)
                else:
                    return int(value)
            except ValueError:
                raise RuntimeError(f"Cannot convert '{value}' to number")
        
        raise RuntimeError(f"Cannot convert {type(value)} to number")
    
    def to_yarn(self, value):
        # convert value to YARN (string)
        if value is None:
            return ""
        
        if isinstance(value, bool):
            return "WIN" if value else "FAIL"
        
        if isinstance(value, float):
            # Truncate to 2 decimal places
            return f"{value:.2f}"
        
        return str(value)
    
    def to_troof(self, value):
        # convert value to TROOF (boolean)
        if value is None:
            return False
        
        if isinstance(value, bool):
            return value
        
        if isinstance(value, (int, float)):
            return value != 0
        
        if isinstance(value, str):
            return value.upper() == "WIN"
        
        return True

    def execute_loop(self, node):
        # Execute a loop statement
        # node.value contains the loop label
        # Children: loop_operation (optional), loop_condition (optional), loop_body
        
        operation_node = None
        condition_node = None
        body_node = None
        
        # Extract child nodes
        for child in node.children:
            if child.type == 'loop_operation':
                operation_node = child
            elif child.type == 'loop_condition':
                condition_node = child
            elif child.type == 'loop_body':
                body_node = child
        
        # Infinite loop protection counter
        max_iterations = 10000
        iteration_count = 0
        
        while True:
            iteration_count += 1
            if iteration_count > max_iterations:
                raise RuntimeError(f"Loop exceeded maximum iterations ({max_iterations})")
            
            # Check condition before loop body (for TIL and WILE)
            if condition_node:
                condition_type = condition_node.value
                condition_expr = condition_node.children[0]
                condition_value = self.evaluate_expression(condition_expr)
                condition_bool = self.to_troof(condition_value)
                
                # TIL: loop until condition is true (while false)
                # WILE: loop while condition is true
                if condition_type == 'TIL':
                    if condition_bool:  # Condition is true, exit loop
                        break
                elif condition_type == 'WILE':
                    if not condition_bool:  # Condition is false, exit loop
                        break
            
            # Execute loop body
            if body_node:
                should_break = False
                for stmt in body_node.children:
                    if stmt.type == 'break':
                        should_break = True
                        break
                    result = self.execute_node(stmt)
                    if isinstance(result, dict) and result.get('type') == 'break':
                        should_break = True
                        break
                if should_break:
                    break
            
            # Perform operation (UPPIN or NERFIN) after body
            if operation_node:
                op_info = operation_node.value
                operation = op_info['operation']
                var_name = op_info['variable']
                
                # Get current value
                if var_name not in self.symbol_table.symbols:
                    raise RuntimeError(f"Loop variable '{var_name}' not declared")
                
                current_value = self.symbol_table.symbols[var_name]
                
                # Convert to number if needed
                if current_value is None:
                    current_value = 0
                else:
                    current_value = self.to_number(current_value)
                
                # Increment or decrement
                if operation == 'UPPIN':
                    new_value = current_value + 1
                elif operation == 'NERFIN':
                    new_value = current_value - 1
                
                # Update variable
                self.symbol_table.symbols[var_name] = new_value
        
        return None
