HAI

OBTW
This is a multi-line comment
Your tokenizer MUST skip all of this
TLDR

WAZZUP
    BTW variable declarations
    I HAS A x ITZ 5
    I HAS A y ITZ 10
    I HAS A msg ITZ "hello"
    I HAS A flag ITZ WIN
    I HAS A nothing
    I HAS A sum ITZ SUM OF x AN y
    I HAS A diff ITZ DIFF OF y AN x
    I HAS A prod ITZ PRODUKT OF x AN 3
    I HAS A quo ITZ QUOSHUNT OF y AN 3
BUHBYE

VISIBLE "=== BASIC LITERALS ==="
VISIBLE x
VISIBLE y
VISIBLE msg
VISIBLE flag
VISIBLE nothing

VISIBLE "=== NESTED EXPRESSIONS ==="
VISIBLE SUM OF PRODUKT OF 3 AN 5 AN BIGGR OF DIFF OF 20 AN 4 AN 5
VISIBLE SMALLR OF SUM OF 5 AN 5 AN PRODUKT OF 2 AN 3

VISIBLE "=== BOOLEAN TESTS ==="
VISIBLE BOTH SAEM 5 AN 5
VISIBLE DIFFRINT 5 AN 10
VISIBLE BOTH OF WIN AN FAIL
VISIBLE EITHER OF WIN AN FAIL
VISIBLE WON OF WIN AN WIN
VISIBLE ANY OF FAIL AN WIN AN FAIL MKAY
VISIBLE ALL OF WIN AN WIN AN FAIL MKAY

VISIBLE "=== UNARY NOT ==="
VISIBLE NOT WIN
VISIBLE NOT FAIL

VISIBLE "=== SMOOSH (FULL TEST) ==="
VISIBLE SMOOSH "Hello" AN " " AN "World!" AN 123
VISIBLE SMOOSH "OneArg"
VISIBLE SMOOSH 5 AN WIN
VISIBLE SMOOSH

VISIBLE "=== ALL OF / ANY OF (EXTENDED) ==="
VISIBLE ALL OF WIN AN WIN AN WIN MKAY
VISIBLE ALL OF WIN AN FAIL AN WIN MKAY
VISIBLE ANY OF FAIL AN FAIL AN WIN MKAY
VISIBLE ANY OF FAIL AN FAIL AN FAIL MKAY

VISIBLE "=== TYPECAST MAEK ==="
VISIBLE MAEK "123" A NUMBR
VISIBLE MAEK 3.14 A YARN
VISIBLE MAEK FAIL A NUMBR
BTW VISIBLE MAEK "hello" A NUMBR   BTW This should error - non-numeric string
VISIBLE MAEK NOOB A YARN
VISIBLE MAEK WIN A YARN
VISIBLE MAEK 0 A TROOF
VISIBLE MAEK 1 A TROOF
BTW VISIBLE MAEK "FALSE" A TROOF  BTW String to TROOF - empty string is FAIL, non-empty is WIN

VISIBLE "=== RECAST IS NOW A ==="
I HAS A z ITZ 5
z IS NOW A YARN
VISIBLE z
z IS NOW A NUMBAR
VISIBLE z

VISIBLE "=== IT VARIABLE CHECKS ==="
I HAS A ittest ITZ SUM OF 2 AN 3
VISIBLE IT
ittest R SUM OF IT AN 10
VISIBLE IT
VISIBLE ittest

VISIBLE "=== IF-ELSE O RLY ==="
VISIBLE "Testing O RLY"
WIN
O RLY?
    YA RLY
        VISIBLE "This should print: YA RLY"
    NO WAI
        VISIBLE "Should NOT print: NO WAI"
OIC

FAIL
O RLY?
    YA RLY
        VISIBLE "Should NOT print"
    NO WAI
        VISIBLE "This should print: NO WAI"
OIC

VISIBLE "=== MEBBE TEST ==="
BTW MEBBE is optional, skipping
VISIBLE "MEBBE not implemented"

VISIBLE "=== SWITCH WTF? ==="
x
WTF?
    OMG 1
        VISIBLE "case 1"
        GTFO
    OMG 5
        VISIBLE "case 5 matched"
        GTFO
    OMG "hello"
        VISIBLE "string case"
    OMGWTF
        VISIBLE "default case"
OIC

VISIBLE "=== SWITCH WITHOUT GTFO ==="
5
WTF?
    OMG 5
        VISIBLE "should match and NOT fall through"
    OMG 10
        VISIBLE "should NOT print"
    OMGWTF
        VISIBLE "should NOT print"
OIC

VISIBLE "=== LOOPS (UPPIN) ==="
I HAS A ctr ITZ 0
IM IN YR loop UPPIN YR ctr TIL BOTH SAEM ctr AN 3
    VISIBLE SMOOSH "loop ctr = " AN ctr
    I HAS A temp ITZ SUM OF ctr AN 1
    VISIBLE temp
IM OUTTA YR loop

VISIBLE "=== LOOPS (NERFIN + GTFO) ==="
I HAS A ctr2 ITZ 3
IM IN YR loop2 NERFIN YR ctr2 WILE DIFFRINT ctr2 AN 0
    VISIBLE SMOOSH "loop2 ctr = " AN ctr2
    BOTH SAEM ctr2 AN 1 O RLY?
        YA RLY
            VISIBLE "breaking out with GTFO"
            GTFO
        NO WAI
    OIC
IM OUTTA YR loop2

VISIBLE "=== LOOP WITH ZERO ITERATIONS ==="
I HAS A c ITZ 5
IM IN YR zloop UPPIN YR c TIL BOTH SAEM 5 AN 5
    VISIBLE "should NOT print"
IM OUTTA YR zloop

VISIBLE "=== FUNCTIONS ==="
HOW IZ I add YR a AN YR b
    FOUND YR SUM OF a AN b
IF U SAY SO

VISIBLE I IZ add YR 10 AN YR 20 MKAY

BTW Factorial function - simplified non-recursive version
BTW Recursive version commented out to avoid complexity
BTW HOW IZ I fact YR n
BTW     BOTH SAEM n AN SMALLR OF n AN 2
BTW     O RLY?
BTW         YA RLY
BTW             FOUND YR 1
BTW         NO WAI
BTW             FOUND YR PRODUKT OF n AN I IZ fact YR DIFF OF n AN 1 MKAY
BTW     OIC
BTW IF U SAY SO
BTW VISIBLE I IZ fact YR 5 MKAY

VISIBLE "Factorial test skipped (recursion complex)"

VISIBLE "=== FUNCTION WITH NO PARAMS ==="
HOW IZ I greet
    FOUND YR "hi!"
IF U SAY SO

VISIBLE I IZ greet MKAY

VISIBLE "=== FUNCTION RETURNING NOOB ==="
HOW IZ I giveNOOB
    I HAS A nuthin
    FOUND YR nuthin
IF U SAY SO

VISIBLE MAEK I IZ giveNOOB MKAY A YARN

KTHXBYE
