# parser/parser.py

#syntacx analyzer parser for the lolcode
# it takes a list of tokens generated by the lexical analyzer (tokenizer) and
#constructs a parse tree (or AST) representing the program's structure.


from .node import Node
from .symbol_table import SymbolTable

class Parser:
    #Initializes the parse using the tokens
    def __init__(self, tokens):
        self.tokens = tokens
        self.position = 0
        self.symbol_table = SymbolTable()

    #get the current token
    def current_token(self):
        if self.position < len(self.tokens):
            return self.tokens[self.position]
        return None

    # advance to the next token
    def advance(self):
        self.position += 1
    
    # match the current token with expected type and value
    def match(self, expected_type, expected_value=None):
        token = self.current_token()
        if token['type'] == expected_type:
            if expected_value is None or token['value'] == expected_value:
                self.advance()
                return token
        err_msg = f"Syntax Error: Expected  '{expected_type}'"
        raise SyntaxError(err_msg)

    #parse the token and creates the AST
    def parse(self):
        return self.parse_program()
    
    # parses the program
    def parse_program(self):
        program_node = Node('program')
        
        # Skip any leading linebreaks (from comments or blank lines before HAI)
        while self.current_token() and self.current_token()['type'] == 'LINEBREAK':
            self.advance()
        
        self.match('HAI')
        self.match('LINEBREAK')
        if self.current_token() and self.current_token()['type'] == 'WAZZUP':
            program_node.add_child(self.parse_variable_declaration_block())
        while self.current_token() and self.current_token()['type'] != 'KTHXBYE':
            # Skip extra linebreaks (from comments or blank lines)
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            
            stmt = self.parse_statement()
            if stmt:
                program_node.add_child(stmt)
            self.match('LINEBREAK')
        self.match('KTHXBYE')
        return program_node

    # parses variable declarations
    def parse_variable_declaration_block(self):
        block_node = Node('variable_declaration_block')
        self.match('WAZZUP')
        self.match('LINEBREAK')
        while self.current_token() and self.current_token()['type'] != 'BUHBYE':
            # Skip any extra linebreaks (from comments or blank lines)
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            
            if self.current_token()['type'] == 'I HAS A':
                 block_node.add_child(self.parse_variable_declaration())
                 self.match('LINEBREAK')
            else:
                # Unknown token in variable declaration block - skip it
                self.advance()
        self.match('BUHBYE')
        self.match('LINEBREAK')
        return block_node

    def parse_statement(self):
        token_type = self.current_token()['type']
        if token_type == 'VISIBLE':
            return self.parse_print_statement()
        elif token_type == 'GIMMEH':
            return self.parse_input_statement()
        elif token_type == 'I HAS A':
            return self.parse_variable_declaration()
        elif token_type == 'IDENTIFIER':
            return self.parse_assignment()
        elif token_type == 'O RLY?':
            return self.parse_orly()
        elif token_type == 'WTF?':
            return self.parse_switch()
        elif token_type == 'IM IN YR':
            return self.parse_loop()
        else:
            # Try to parse as expression statement (result goes to IT)
            expr = self.parse_expression()
            if expr:
                return Node('expression_statement', children=[expr])
            return None
    
    def parse_switch(self):
        #math wtf?
        self.match('WTF?')
        node = Node ('switch_statement')

        #parse cases
        while self.current_token() and self.current_token()['type'] != 'OIC':
            tok = self.current_token()['type']

            # OMG <literal>
            if tok == 'OMG':
                node.add_child(self.parse_switch_case())
            
            # OMGWTF (default case)
            elif tok == 'OMGWTF':
                node.add_child(self.parse_default_case())

            # Skip blank lines
            elif tok == 'LINEBREAK':
                self.advance()
            else:
                raise SyntaxError(f"Unexpected token in switch: {tok}")

        # END OF SWITCH
        self.match('OIC')
        return node
    
    def parse_switch_case(self):
        self.match('OMG')
        case_value = self.parse_literal()  # literal only
        case_node = Node('case', value=case_value.value)

        # Parse the case block
        while self.current_token() and self.current_token()['type'] not in ('OMG', 'OMGWTF', 'OIC'):
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                case_node.add_child(Node('break'))
                break
            
            stmt = self.parse_statement()
            if stmt:
                case_node.add_child(stmt)

            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()

        return case_node

    def parse_default_case(self):
        self.match('OMGWTF')
        default_node = Node('default_case')

        while self.current_token() and self.current_token()['type'] not in ('OIC',):
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                default_node.add_child(Node('break'))
                break

            stmt = self.parse_statement()
            if stmt:
                default_node.add_child(stmt)

            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()

        return default_node


    def parse_orly(self):
        # O RLY? node
        self.match('O RLY?')
        self.match('LINEBREAK')
        node = Node('orly_statement')

        # YA RLY block 
        self.match('YA RLY')
        self.match('LINEBREAK')
        ya_node = Node('ya_rly')
        while self.current_token() and self.current_token()['type'] not in ('MEBBE', 'NO WAI', 'OIC'):
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                ya_node.add_child(Node('break'))
                if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
                continue
            stmt = self.parse_statement()
            if stmt:
                ya_node.add_child(stmt)
            if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                self.advance()
        node.add_child(ya_node)

        # NO WAI block
        if self.current_token() and self.current_token()['type'] == 'NO WAI':
            self.advance()
            self.match('LINEBREAK')
            nowai_node = Node('no_wai')
            while self.current_token() and self.current_token()['type'] != 'OIC':
                if self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
                    continue
                if self.current_token()['type'] == 'GTFO':
                    self.match('GTFO')
                    nowai_node.add_child(Node('break'))
                    if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                        self.advance()
                    continue
                stmt = self.parse_statement()
                if stmt:
                    nowai_node.add_child(stmt)
                if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
            node.add_child(nowai_node)

        self.match('OIC')
        return node

    def parse_variable_declaration(self):
        self.match('I HAS A')
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        node = Node('variable_declaration', value=var_name)
        initial_value = None
        if self.current_token() and self.current_token()['type'] == 'ITZ':
            self.match('ITZ')
            expr_node = self.parse_expression()
            node.add_child(expr_node)
            initial_value = expr_node
        self.symbol_table.declare(var_name, initial_value)
        return node

    def parse_assignment(self):
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        self.symbol_table.lookup(var_name)
        node = Node('assignment', value=var_name)
        self.match('R')
        expr_node = self.parse_expression()
        node.add_child(expr_node)
        self.symbol_table.update(var_name, expr_node)
        return node

    def parse_print_statement(self):
        self.match('VISIBLE')
        node = Node('print_statement')
        # VISIBLE can have multiple expressions separated by spaces or AN
        while self.current_token() and self.current_token()['type'] != 'LINEBREAK':
            expr_node = self.parse_expression()
            if expr_node:  # Only add if expression was successfully parsed
                node.add_child(expr_node)
            # Check if there's an AN separator or just continue with next expression
            if self.current_token() and self.current_token()['type'] == 'AN':
                self.advance()  # Skip the AN
            elif self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                break  # Stop at linebreak
        return node

    #Added for User Input GIMMEH
    def parse_input_statement(self):
        self.match('GIMMEH')
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        self.symbol_table.lookup(var_name)
        return Node('input_statement', value=var_name)

    def parse_expression(self):
        token = self.current_token()
        if not token or token['type'] == 'LINEBREAK':
            return None
        operation_types = ['SUM OF', 'DIFF OF', 'PRODUKT OF', 'QUOSHUNT OF', 'MOD OF', 'BIGGR OF', 'SMALLR OF', 'BOTH SAEM', 'DIFFRINT']
        if token['type'] in operation_types:
            return self.parse_binary_operation()
        elif 'Literal' in token['type']:
            return self.parse_literal()
        elif token['type'] == 'IDENTIFIER':
            self.symbol_table.lookup(token['value'])
            return Node('variable', value=self.match('IDENTIFIER')['value'])

    def parse_literal(self):
        token = self.current_token()
        if token['type'] == 'NUMBR Literal':
            return Node('literal_numbr', value=int(self.match('NUMBR Literal')['value']))
        elif token['type'] == 'NUMBAR Literal':
            return Node('literal_numbar', value=float(self.match('NUMBAR Literal')['value']))
        elif token['type'] == 'YARN Literal':
            yarn_value = self.match('YARN Literal')['value']
            return Node('literal_yarn', value=yarn_value[1:-1])
        elif token['type'] == 'TROOF Literal':
            return Node('literal_troof', value=self.match('TROOF Literal')['value'])

    def parse_binary_operation(self):
        op_token = self.current_token()
        self.advance()
        node = Node('binary_operation', value=op_token['type'])
        left_expr = self.parse_expression()
        node.add_child(left_expr)
        self.match('AN')
        right_expr = self.parse_expression()
        node.add_child(right_expr)
        return node

    def parse_loop(self):
        # IM IN YR <label> <operation> YR <variable> [TIL|WILE <expression>] ... IM OUTTA YR <label>
        self.match('IM IN YR')
        label_token = self.match('IDENTIFIER')
        label = label_token['value']
        
        loop_node = Node('loop', value=label)
        
        # Check for operation (UPPIN or NERFIN)
        operation_token = self.current_token()
        if operation_token['type'] in ('UPPIN', 'NERFIN'):
            operation = operation_token['type']
            self.advance()
            self.match('YR')
            var_token = self.match('IDENTIFIER')
            var_name = var_token['value']
            
            # Create operation node
            op_node = Node('loop_operation', value={'operation': operation, 'variable': var_name})
            loop_node.add_child(op_node)
        
        # Check for condition (TIL or WILE)
        condition_token = self.current_token()
        if condition_token['type'] in ('TIL', 'WILE'):
            condition_type = condition_token['type']
            self.advance()
            condition_expr = self.parse_expression()
            
            # Create condition node
            cond_node = Node('loop_condition', value=condition_type)
            cond_node.add_child(condition_expr)
            loop_node.add_child(cond_node)
        
        # Parse loop body
        self.match('LINEBREAK')
        body_node = Node('loop_body')
        
        while self.current_token() and self.current_token()['type'] != 'IM OUTTA YR':
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                body_node.add_child(Node('break'))
                if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
                continue
            
            stmt = self.parse_statement()
            if stmt:
                body_node.add_child(stmt)
                
            # Consume linebreak after statement
            if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                self.advance()
        
        loop_node.add_child(body_node)
        
        # Match loop terminator
        self.match('IM OUTTA YR')
        end_label_token = self.match('IDENTIFIER')
        
        if end_label_token['value'] != label:
            raise SyntaxError(f"Loop label mismatch: expected '{label}', got '{end_label_token['value']}'")
        
        return loop_node