# parser/parser.py

#syntacx analyzer parser for the lolcode
# it takes a list of tokens generated by the lexical analyzer (tokenizer) and
#constructs a parse tree (or AST) representing the program's structure.

from .node import Node
from .symbol_table import SymbolTable

class Parser:
    #Initializes the parse using the tokens
    def __init__(self, tokens):
        self.tokens = tokens
        self.position = 0
        self.symbol_table = SymbolTable()
        self.symbol_table.symbols['IT'] = None

    #get the current token
    def current_token(self):
        if self.position < len(self.tokens):
            return self.tokens[self.position]
        return None

    # advance to the next token
    def advance(self):
        self.position += 1
    
    #peek at the next token without advancing
    def peek(self):
        if self.position + 1 < len(self.tokens):
            return self.tokens[self.position + 1]
        return None
    
    # match the current token with expected type and value
    def match(self, expected_type, expected_value=None):
        token = self.current_token()
        if token is None:
            raise SyntaxError(f"Unexpected end of file. Expected '{expected_type}'")
        if token['type'] == expected_type:
            if expected_value is None or token['value'] == expected_value:
                self.advance()
                return token
        err_msg = f"Syntax Error: Expected  '{expected_type}'"
        raise SyntaxError(err_msg)

    #parse the token and creates the AST
    def parse(self):
        return self.parse_program()
    
    # parses the program
    def parse_program(self):
        program_node = Node('program')
        while self.current_token() and self.current_token()['type'] == 'LINEBREAK':
            self.advance()
        self.match('HAI')
        self.match('LINEBREAK')
        while self.current_token() and self.current_token()['type'] == 'LINEBREAK':
            self.advance()
        if self.current_token() and self.current_token()['type'] == 'WAZZUP':
            program_node.add_child(self.parse_variable_declaration_block())
        while True:
            if not self.current_token() or self.current_token()['type'] == 'KTHXBYE':
                break 
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            stmt = self.parse_statement()
            if stmt:
                program_node.add_child(stmt)
            if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                self.advance()
            else:
                if self.current_token() and self.current_token()['type'] != 'KTHXBYE':
                    raise SyntaxError(f"Expected LINEBREAK after statement, but got {self.current_token()['type']}")
        self.match('KTHXBYE')
        return program_node

    # parses variable declarations
    def parse_variable_declaration_block(self):
        block_node = Node('variable_declaration_block')
        self.match('WAZZUP')
        self.match('LINEBREAK')
        while self.current_token() and self.current_token()['type'] != 'BUHBYE':
            # Skip any extra linebreaks (from comments or blank lines)
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            
            if self.current_token()['type'] == 'I HAS A':
                 block_node.add_child(self.parse_variable_declaration())
                 self.match('LINEBREAK')
            else:
                # Unknown token in variable declaration block - skip it
                self.advance()
        self.match('BUHBYE')
        self.match('LINEBREAK')
        return block_node

    # parses a single statement
    def parse_statement(self):
        token = self.current_token()
        if not token: 
            return None
        token_type = token['type']
        if token_type == 'OBTW':
            self.parse_multiline_comment()
            return None
        if token_type == 'VISIBLE':
            return self.parse_print_statement()
        elif token_type == 'GIMMEH':
            return self.parse_input_statement()
        elif token_type == 'I HAS A':
            return self.parse_variable_declaration()
        elif token_type == 'IDENTIFIER':
            next_token = self.peek()
            if next_token:
                if next_token['type'] == 'IS NOW A': return self.parse_recast()
                elif next_token['type'] == 'R': return self.parse_assignment()
            expr = self.parse_expression()
            if expr: return Node('expression_statement', children=[expr])
            return None
        elif token_type == 'O RLY?':
            return self.parse_orly()
        elif token_type == 'WTF?':
            return self.parse_switch()
        elif token_type == 'HOW IZ I':
            return self.parse_function_definition()
        elif token_type == 'I IZ':
            return self.parse_function_call()
        elif token_type == 'FOUND YR':
            return self.parse_return_statement()
        elif token_type == 'IM IN YR':
            return self.parse_loop()
        elif token_type == 'GTFO':
            self.match('GTFO')
            return Node('break')
        else:
            expr = self.parse_expression()
            if expr:
                return Node('expression_statement', children=[expr])
            raise SyntaxError(f"Invalid statement start: '{token_type}'")

    # parses function definition
    def parse_function_definition(self):
        self.match('HOW IZ I')
        func_name = self.match('IDENTIFIER')['value']

        #parse parameters
        params = []
        if self.current_token()['type'] == 'YR':
            while True:
                self.match('YR')
                param_name = self.match('IDENTIFIER')['value']
                params.append(param_name)
                # Declare parameter in symbol table for the function body parsing
                if param_name not in self.symbol_table.symbols:
                    self.symbol_table.symbols[param_name] = None

                if self.current_token()['type'] != 'AN':
                    break
                self.match('AN')
        func_node = Node('function_def', value=func_name)
        func_node.params = params

        #parse function body
        #body until IF U SAY SO
        while self.current_token()['type'] != 'IF U SAY SO':
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            stmt = self.parse_statement()
            if stmt:
                func_node.add_child(stmt)
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
        
        self.match('IF U SAY SO')
        return func_node
    
    def parse_function_call(self):
        self.match('I IZ')
        func_name = self.match('IDENTIFIER')['value']

        args = []
        if self.current_token() and self.current_token()['type'] == 'YR':
            while True:
                self.match('YR')
                expr = self.parse_expression()
                args.append(expr)

                if not self.current_token() or self.current_token()['type'] != 'AN':
                    break
                self.match('AN')
        # MKAY is optional (used when function call is in an expression, not needed as statement)
        if self.current_token() and self.current_token()['type'] == 'MKAY':
            self.match('MKAY')
        call_node = Node('function_call', value=func_name)
        for a in args:
            call_node.add_child(a)
        return call_node
    
    def parse_return_statement(self):
        self.match('FOUND YR')
        expr = self.parse_expression()
        return Node('return', children=[expr])

     #parses WTF? OMG, OMGWTF OIC structure
    def parse_switch(self):
        #math wtf?
        self.match('WTF?')
        node = Node ('switch_statement')

        #parse cases bock untils oic
        while self.current_token() and self.current_token()['type'] != 'OIC':
            tok = self.current_token()['type']

            # OMG <literal>
            if tok == 'OMG':
                node.add_child(self.parse_switch_case())
            
            # OMGWTF (default case)
            elif tok == 'OMGWTF':
                node.add_child(self.parse_default_case())

            # Skip blank lines
            elif tok == 'LINEBREAK':
                self.advance()
            else:
                raise SyntaxError(f"Unexpected token in switch: {tok}")

        # end of switch case
        self.match('OIC')
        return node
    #parse a single omg case block
    #stops paring when next omg, omgwtf oic
    def parse_switch_case(self):
        self.match('OMG')
        case_value = self.parse_literal()
        case_node = Node('case', value=case_value.value)
        case_node.add_child(Node("literal", value=case_value.value))
   
        while self.current_token() and self.current_token()['type'] not in ('OMG', 'OMGWTF', 'OIC'):
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                case_node.add_child(Node('break'))
                break

            stmt = self.parse_statement()
            if stmt:
                case_node.add_child(stmt)
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()

        return case_node
    
    #parses the omgwtf default case
    def parse_default_case(self):
        self.match('OMGWTF')
        default_node = Node('default_case')

        while self.current_token() and self.current_token()['type'] not in ('OIC',):
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                default_node.add_child(Node('break'))
                break

            stmt = self.parse_statement()
            if stmt:
                default_node.add_child(stmt)

            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()

        return default_node

    #parses O RLY? YA RLY, MEBBE, NO WAI OIC structure
    def parse_orly(self):
        self.match('O RLY?')
        if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
            self.advance()
        node = Node('orly_statement')
        self.match('YA RLY')
        if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
            self.advance()
        ya_node = Node('ya_rly')
        while self.current_token() and self.current_token()['type'] not in ('MEBBE', 'NO WAI', 'OIC'):
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue
            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                ya_node.add_child(Node('break'))
                if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
                continue
            stmt = self.parse_statement()
            if stmt:
                ya_node.add_child(stmt)
                self.match('LINEBREAK')
            else:
                if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
        node.add_child(ya_node)

        if self.current_token() and self.current_token()['type'] == 'NO WAI':
            self.advance()
            if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                self.advance()
            nowai_node = Node('no_wai')
            
            while self.current_token() and self.current_token()['type'] != 'OIC':
                if self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
                    continue
                if self.current_token()['type'] == 'GTFO':
                    self.match('GTFO')
                    nowai_node.add_child(Node('break'))
                    if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                        self.advance()
                    continue
                
                stmt = self.parse_statement()
                if stmt:
                    nowai_node.add_child(stmt)
                    self.match('LINEBREAK')
                else:
                    if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                        self.advance()             
            node.add_child(nowai_node)
        self.match('OIC')
        return node

    # parses variable declaration
    def parse_variable_declaration(self):
        self.match('I HAS A')
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        node = Node('variable_declaration', value=var_name)
        initial_value = None
        if self.current_token() and self.current_token()['type'] == 'ITZ':
            self.match('ITZ')
            expr_node = self.parse_expression()
            node.add_child(expr_node)
            initial_value = expr_node
        self.symbol_table.declare(var_name, initial_value)
        return node

    # parses variable assignment
    def parse_assignment(self):
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        self.symbol_table.lookup(var_name)
        node = Node('assignment', value=var_name)
        self.match('R')
        expr_node = self.parse_expression()
        node.add_child(expr_node)
        self.symbol_table.update(var_name, expr_node)
        return node

    # parses type recasting
    def parse_recast(self):
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        self.symbol_table.lookup(var_name)
        self.match('IS NOW A')
        target_type = self.current_token()['value']
        self.advance()
        node = Node('recast_statement', value=var_name)
        node.add_child(Node('type', value=target_type))
        return node

    #parses print statement
    def parse_print_statement(self):
        self.match('VISIBLE')
        node = Node('print_statement')
        while self.current_token() and self.current_token()['type'] != 'LINEBREAK':
            expr_node = self.parse_expression()
            if expr_node:
                node.add_child(expr_node)
            else:
                break
            if self.current_token() and self.current_token()['type'] == 'AN':
                self.advance()
            elif self.current_token() and self.current_token()['type'] == 'CONCAT':
                self.advance()  
            elif self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                break 
            elif self.current_token() and self.current_token()['type'] in ['NUMBR Literal', 'NUMBAR Literal', 'YARN Literal', 'TROOF Literal', 'IDENTIFIER', 'SUM OF', 'DIFF OF', 'PRODUKT OF', 'QUOSHUNT OF', 'MOD OF', 'BIGGR OF', 'SMALLR OF', 'BOTH SAEM', 'DIFFRINT', 'BOTH OF', 'EITHER OF', 'WON OF', 'NOT', 'SMOOSH', 'ALL OF', 'ANY OF', 'MAEK', 'I IZ', 'TYPE Literal']:
                continue  
            else:
                break  
        return node

    #Added for User Input GIMMEH
    def parse_input_statement(self):
        self.match('GIMMEH')
        var_name_token = self.match('IDENTIFIER')
        var_name = var_name_token['value']
        self.symbol_table.lookup(var_name)
        return Node('input_statement', value=var_name)

    # parses expressions
    def parse_expression(self):
        token = self.current_token()
        if not token or token['type'] == 'LINEBREAK':
            return None
        
        # Binary arithmetic and comparison operations
        binary_ops = ['SUM OF', 'DIFF OF', 'PRODUKT OF', 'QUOSHUNT OF', 'MOD OF', 
                      'BIGGR OF', 'SMALLR OF', 'BOTH SAEM', 'DIFFRINT']
        
        # Binary boolean operations
        boolean_binary_ops = ['BOTH OF', 'EITHER OF', 'WON OF']
        
        if token['type'] in binary_ops:
            return self.parse_binary_operation()
        elif token['type'] in boolean_binary_ops:
            return self.parse_binary_operation()
        elif token['type'] == 'NOT':
            return self.parse_not_operation()
        elif token['type'] == 'SMOOSH':
            return self.parse_smoosh()
        elif token['type'] in ['ALL OF', 'ANY OF']:
            return self.parse_infinite_arity_boolean()
        elif token['type'] == 'MAEK':
            return self.parse_maek()
        elif token['type'] == 'I IZ':
            return self.parse_function_call_expr()
        elif token['type'] in ['NUMBR Literal', 'NUMBAR Literal', 'YARN Literal', 'TROOF Literal']:
            return self.parse_literal()
        elif token['type'] == 'TYPE Literal' and token['value'] == 'NOOB':
            self.advance()
            return Node('literal_noob', value=None)
        elif token['type'] == 'IDENTIFIER':
            if self.peek() and self.peek()['type'] == 'YR':
                 return self.parse_function_call()
            self.symbol_table.lookup(token['value'])
            return Node('variable', value=self.match('IDENTIFIER')['value'])
        else:
            return None

    # parses function call expression
    def parse_function_call_expr(self):
        self.match('I IZ')
        func_name = self.match('IDENTIFIER')['value']

        args = []
        if self.current_token() and self.current_token()['type'] == 'YR':
            while True:
                self.match('YR')
                expr = self.parse_expression()
                args.append(expr)

                if not self.current_token() or self.current_token()['type'] != 'AN':
                    break
                self.match('AN')
        if self.current_token() and self.current_token()['type'] == 'MKAY':
            self.match('MKAY')
        call_node = Node('function_call', value=func_name)
        for a in args:
            call_node.add_child(a)
        return call_node

    # parses NOT operation
    def parse_not_operation(self):
        self.match('NOT')
        operand = self.parse_expression()
        return Node('unary_operation', value='NOT', children=[operand])

    # parses SMOOSH operation
    def parse_smoosh(self):
        self.match('SMOOSH')
        node = Node('variadic_operation', value='SMOOSH')
        # Parse first operand (if any)
        first_expr = self.parse_expression()
        if first_expr:
            node.add_child(first_expr)
            # Parse additional operands separated by AN
            while self.current_token() and self.current_token()['type'] == 'AN':
                self.advance()  # consume AN
                expr = self.parse_expression()
                if expr:
                    node.add_child(expr)
                else:
                    break
        return node

    # parses ALL OF and ANY OF operations
    def parse_infinite_arity_boolean(self):
        op_type = self.current_token()['type']
        self.match(op_type)
        node = Node('variadic_operation', value=op_type)
        # Parse first operand
        first_expr = self.parse_expression()
        if first_expr:
            node.add_child(first_expr)
        # Parse additional operands separated by AN until MKAY
        while self.current_token() and self.current_token()['type'] == 'AN':
            self.advance()  # consume AN
            expr = self.parse_expression()
            if expr:
                node.add_child(expr)
        # Consume MKAY
        if self.current_token() and self.current_token()['type'] == 'MKAY':
            self.match('MKAY')
        return node

    # parses MAEK operation
    def parse_maek(self):
        self.match('MAEK')
        # Handle optional leading 'A' (MAEK A <expr> <type>)
        if self.current_token() and self.current_token()['type'] == 'A':
            self.match('A')
        # Parse the expression to cast
        expr = self.parse_expression()
        # Optional 'A' keyword before type (MAEK <expr> A <type>)
        if self.current_token() and self.current_token()['type'] == 'A':
            self.match('A')
        # Get target type
        target_type = self.current_token()['value']
        self.advance()
        return Node('maek_operation', children=[expr, Node('type', value=target_type)])

    # parses literals
    def parse_literal(self):
        token = self.current_token()
        if token['type'] == 'NUMBR Literal':
            return Node('literal_numbr', value=int(self.match('NUMBR Literal')['value']))
        elif token['type'] == 'NUMBAR Literal':
            return Node('literal_numbar', value=float(self.match('NUMBAR Literal')['value']))
        elif token['type'] == 'YARN Literal':
            yarn_value = self.match('YARN Literal')['value']
            # value already has quotes stripped by tokenizer
            return Node('literal_yarn', value=yarn_value)
        elif token['type'] == 'TROOF Literal':
            return Node('literal_troof', value=self.match('TROOF Literal')['value'])

    # parses binary operations
    def parse_binary_operation(self):
        op_token = self.current_token()
        self.advance()
        node = Node('binary_operation', value=op_token['type'])
        left_expr = self.parse_expression()
        node.add_child(left_expr)
        self.match('AN')
        right_expr = self.parse_expression()
        node.add_child(right_expr)
        return node

    # parses loop structure
    def parse_loop(self):
        # IM IN YR <label> <operation> YR <variable> [TIL|WILE <expression>] ... IM OUTTA YR <label>
        self.match('IM IN YR')
        label_token = self.match('IDENTIFIER')
        label = label_token['value']

        loop_node = Node('loop', value=label)

        # Check for operation (UPPIN or NERFIN)
        operation_token = self.current_token()
        if operation_token and operation_token['type'] in ('UPPIN', 'NERFIN'):
            operation = operation_token['type']
            self.advance()
            self.match('YR')
            var_token = self.match('IDENTIFIER')
            var_name = var_token['value']

            # Create operation node
            op_node = Node('loop_operation', value={'operation': operation, 'variable': var_name})
            loop_node.add_child(op_node)

        # Check for condition (TIL or WILE)
        condition_token = self.current_token()
        if condition_token and condition_token['type'] in ('TIL', 'WILE'):
            condition_type = condition_token['type']
            self.advance()
            condition_expr = self.parse_expression()

            # Create condition node
            cond_node = Node('loop_condition', value=condition_type)
            cond_node.add_child(condition_expr)
            loop_node.add_child(cond_node)

        # Parse loop body
        self.match('LINEBREAK')
        body_node = Node('loop_body')

        while self.current_token() and self.current_token()['type'] != 'IM OUTTA YR':
            if self.current_token()['type'] == 'LINEBREAK':
                self.advance()
                continue

            if self.current_token()['type'] == 'GTFO':
                self.match('GTFO')
                body_node.add_child(Node('break'))
                if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                    self.advance()
                continue

            stmt = self.parse_statement()
            if stmt:
                body_node.add_child(stmt)

            # Consume linebreak after statement
            if self.current_token() and self.current_token()['type'] == 'LINEBREAK':
                self.advance()

        loop_node.add_child(body_node)

        # Match loop terminator
        self.match('IM OUTTA YR')
        end_label_token = self.match('IDENTIFIER')

        if end_label_token['value'] != label:
            raise SyntaxError(f"Loop label mismatch: expected '{label}', got '{end_label_token['value']}'")

        return loop_node
    
    # parses multiline comments
    def parse_multiline_comment(self):
        self.match('OBTW')
        while self.current_token() and self.current_token()['type'] != 'TLDR':
            self.advance()
        
        self.match('TLDR')
        return None