TOKEN_SPECIFICATION = [
    # Multi Word Keywords
    ('I HAS A', r'I HAS A'),
    ('HAI', r'HAI'),
    ('KTHXBYE', r'KTHXBYE'),
    ('WAZZUP', r'WAZZUP'),
    ('BUHBYE', r'BUHBYE'),
    ('BTW', r'BTW'),
    ('OBTW', r'OBTW'),
    ('TLDR', r'TLDR'),
    ('SUM OF', r'SUM OF'),
    ('DIFF OF', r'DIFF OF'),
    ('PRODUKT OF', r'PRODUKT OF'),
    ('QUOSHUNT OF', r'QUOSHUNT OF'),
    ('MOD OF', r'MOD OF'),
    ('BIGGR OF', r'BIGGR OF'),
    ('SMALLR OF', r'SMALLR OF'),
    ('BOTH OF', r'BOTH OF'),
    ('EITHER OF', r'EITHER OF'),
    ('WON OF', r'WON OF'),
    ('ANY OF', r'ANY OF'),
    ('ALL OF', r'ALL OF'),
    ('BOTH SAEM', r'BOTH SAEM'),
    ('IS NOW A', r'IS NOW A'),
    ('O RLY?', r'O RLY\?'),
    ('YA RLY', r'YA RLY'),
    ('NO WAI', r'NO WAI'),
    ('ITZ', r'ITZ'),
    ('R', r'R'),
    ('NOT', r'NOT'),
    ('DIFFRINT', r'DIFFRINT'),
    ('SMOOSH', r'SMOOSH'),
    ('MAEK', r'MAEK'),
    ('A', r'A'),
    ('VISIBLE', r'VISIBLE'),
    ('GIMMEH', r'GIMMEH'),
    ('IM IN YR', r'IM IN YR'),
    ('IM OUTTA YR', r'IM OUTTA YR'),
    ('HOW IZ I', r'HOW IZ I'),
    ('IF U SAY SO', r'IF U SAY SO'),
    ('FOUND YR', r'FOUND YR'),
    ('I IZ', r'I IZ'),


    # Literals
    ('NUMBAR Literal', r'-?[0-9]+\.[0-9]+'),
    ('NUMBR Literal', r'-?[0-9]+'),
    ('YARN Literal', r'"[^"]*"'),
    ('TROOF Literal', r'(WIN|FAIL)'),
    ('TYPE Literal', r'(NOOB|NUMBR|NUMBAR|YARN|TROOF)'),

   
    #Single Word Keywords
    ('MEBBE', r'MEBBE'),
    ('OIC', r'OIC'),
    ('WTF?', r'WTF\?'),
    ('OMG', r'OMG'),
    ('OMGWTF', r'OMGWTF'),
    ('UPPIN', r'UPPIN'),
    ('NERFIN', r'NERFIN'),
    ('YR', r'YR'),
    ('TIL', r'TIL'),
    ('WILE', r'WILE'),
    ('GTFO', r'GTFO'),
    ('MKAY', r'MKAY'),
    ('AN', r'AN'),


    # Identifier and Miscellaneous
    ('IDENTIFIER', r'[a-zA-Z][a-zA-Z0-9]*'),
    ('linebreak', r'\n'),
    ('WHITESPACE', r'[ \t\r]+'),
]